[tool.pytest.ini_options]
python_classes = ["Test", "Describe"]
python_functions = ["test_", "it_", "and_", "but_", "they_"]
python_files = ["test_*.py",]
testpaths = ["test", "test/docker_tests"]
norecursedirs = [".git", ".venv", "venv", "node_modules", "__pycache__", "*.egg-info", "build", "dist", "tmp", "api", "log"]
markers = [
	"docker: requires docker socket and elevated container permissions",
	"compose: Tests docker compose files. Slow.",
	"feature_complete: extended coverage suite not run by default",
]
[tool.ruff]
line-length = 180
ignore = ["E203", "C901"]  # global ignores

[tool.ruff.lint]
select = ["E", "F"]
extend-select = ["E402"]